name: YourPet backend release

on:
  workflow_dispatch:
  push:
    branches: [backend-release-pipeline]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: start
        run: echo "hello world"

      - name: setup-java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: "checkout"
        uses: actions/checkout@v2

      - name: build-backend
        run: ./gradlew backend:jvmJar

      - name: build-docker-backend
        run: docker build -t yourpet:latest .

