name: YourPet backend release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'setup java'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: 'checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'build backend'
        run: ./gradlew backend:jvmJar

      - name: 'build docker backend'
        run: docker build -t europe-southwest1-docker.pkg.dev/yourpet-backend/backend-images/yourpet:latest .

      - name: 'login gcloud'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v1

      - name: 'Configure docker to use gcloud'
        run: gcloud auth configure-docker europe-southwest1-docker.pkg.dev

      - name: 'push image to artifact repository'
        run: docker push europe-southwest1-docker.pkg.dev/yourpet-backend/backend-images/yourpet:latest

