name: YourPet backend release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: start
        run: echo "hello world"

      - name: build-backend
        run: ./gradlew backend:jvmJar
