name: YourPet CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  quality:
    runs-on: macos-latest

    steps:
      - name: setup-java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: "checkout"
        uses: actions/checkout@v2

      - name: "install maestro"
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: "export path"
        run: export PATH="$PATH":"$HOME/.maestro/bin"

      - name: "e2e tests"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: pixel_4
          script: |
            maestro test automation/open-list.yaml

      - name: "iOS tests"
        run: |
          xcodebuild test \
          -project iOSApp/iOSApp.xcodeproj \
          -scheme iosApp -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.2' | xcpretty -s

      - name: "run detekt"
        run: ./gradlew detektAll

      - name: "tests"
        run: ./gradlew testDebugUnitTest

#  screenshot-tests:
#    runs-on: macos-latest
#    steps:
#      - name: setup-java
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'temurin'
#          java-version: '11'
#      - name: checkout
#        uses: actions/checkout@v2
#
#      - name: run tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          profile: pixel_4
#          script: |
#            adb shell settings put global hidden_api_policy 1
#            adb shell wm density
#            adb shell wm size
#            ./gradlew executeScreenshotTests
#
#      - name: Commit screenshots
#        run: |
#          git config --local user.email "github-ci@keller.com"
#          git config --local user.name "github-actions[bot]"
#          git commit -m "Add screenshots" -a
#
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}
