name: YourPet CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  quality:
    runs-on: macos-latest

    steps:
      - name: install-idb
        run: |
          brew tap facebook/fb
          brew install idb-companion
      - name: setup-java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: "checkout"
        uses: actions/checkout@v2

      - name: "iOS tests"
        run: |
          xcodebuild test \
          -project iOSApp/iOSApp.xcodeproj \
          -scheme iosApp -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.2'

      - name: "run detekt"
        run: ./gradlew detektAll

      - name: "tests"
        run: ./gradlew testDebugUnitTest

      - name: "install maestro"
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
          export PATH="$PATH":"$HOME/.maestro/bin"
          echo "Maestro version: $(maestro --version)"

      - name: "Build iOS app"
        run: |
          xcodebuild -project iOSApp/iOSApp.xcodeproj \
          -scheme iosApp \
          -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.2' \
          -derivedDataPath build

      - name: "Start backend"
        run: ./gradlew backend:run -Ptesting=true &

      - name: "launch iOS simulator"
        uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 8'
          shutdown_after_job: false

      - name: "ios e2e tests"
        run: |
            xcrun simctl install booted build/Build/Products/Debug-iphonesimulator/iosApp.app
            maestro test automation/open-list.yaml
            xcrun simctl shutdown all

      - name: "Android e2e tests"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: pixel_4
          script: |
            ./gradlew androidApp:installDebug
            maestro test automation/open-list.yaml

#  screenshot-tests:
#    runs-on: macos-latest
#    steps:
#      - name: setup-java
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'temurin'
#          java-version: '11'
#      - name: checkout
#        uses: actions/checkout@v2
#
#      - name: run tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          profile: pixel_4
#          script: |
#            adb shell settings put global hidden_api_policy 1
#            adb shell wm density
#            adb shell wm size
#            ./gradlew executeScreenshotTests
#
#      - name: Commit screenshots
#        run: |
#          git config --local user.email "github-ci@keller.com"
#          git config --local user.name "github-actions[bot]"
#          git commit -m "Add screenshots" -a
#
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}
