name: detekt

on:
  push:
    branches: [ master ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "run detekt"
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: detektAll
