name: detekt

on:
  push:
    branches: [ master ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "run detekt"
        run: ./gradlew detektAll

      - name: "tests"
        run: ./gradlew testDebugUnitTest
